"""empty message

Revision ID: b225d26d6c83
Revises: 7b265237c1aa
Create Date: 2023-03-01 17:47:58.739400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b225d26d6c83'
down_revision = '7b265237c1aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_people', schema=None) as batch_op:
        batch_op.drop_constraint('user_people_people_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'people', ['people_id'], ['name'])

    with op.batch_alter_table('user_planet', schema=None) as batch_op:
        batch_op.drop_constraint('user_planet_planet_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'planets', ['planet_id'], ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_planet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_planet_planet_id_fkey', 'planets', ['planet_id'], ['id'])

    with op.batch_alter_table('user_people', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_people_people_id_fkey', 'people', ['people_id'], ['id'])

    # ### end Alembic commands ###
